name: CI

on:
  pull_request:
    branches:
      - "*"

jobs:
  all:
    name: CI
   
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.15.6]
        target: ["all",]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Setup Go binary path
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Git line endings
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Check out THIS code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}


      - name: Check out the BOOTY code into the Go module directory
        uses: actions/checkout@v2
        with:
          repository: getcouragenow/booty
          path: ${{ github.workspace }}/go/src/github.com/getcouragenow/booty
          
     
      - name: make ${{ matrix.target }}
        run: |
          # workaround for https://github.com/actions/setup-go/issues/14
          #export GOPATH=${GITHUB_WORKSPACE}/go
          #export PATH=$PATH:$GOPATH/bin
          make $target
        working-directory: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}
        env:
          target: ${{ matrix.target }}

    